image: golang:1.14
stages:
  - init
  - test
  - build
  - release
  - package
  - publish

init:
  stage: init
  image: usvc/ci:go-dependencies
  cache:
    key: ${CI_PROJECT_REF}_${CI_COMMIT_REF_NAME}
    paths: ["./vendor"]
  artifacts:
    expire_in: 1 day
    paths: ["./vendor"]
  script: ["entrypoint"]

unit test:
  stage: test
  image: usvc/ci:go-test
  dependencies: ["init"]
  artifacts:
    expire_in: 1 day
    paths: ["./c.out"]
  script:
    - entrypoint

.build:
  image: usvc/ci:go-build-production
  dependencies: ["init"]
  artifacts:
    expire_in: 1 day
    paths: ["./bin/*"]
  script:
    - git fetch
    - CMD_ROOT=config GOOS=linux GOARCH=amd64 entrypoint
    - CMD_ROOT=config GOOS=darwin GOARCH=amd64 entrypoint
    - CMD_ROOT=config GOOS=windows GOARCH=386 BIN_EXT=.exe entrypoint
test build:
  extends: .build
  stage: test
  only: ["master"]
build:
  extends: .build
  stage: build
  only: ["tags"]

version bump:
  stage: release
  only:
    - master
  image: usvc/semver:gitlab-latest
  before_script:
    - apk update && apk upgrade
    - apk add openssh
    - mkdir -p ~/.ssh
    - 'printf -- "${DEPLOY_KEY}" | base64 -d > ~/.ssh/id_rsa'
    - chmod 600 -R ~/.ssh/id_rsa
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
  script:
    - git remote set-url origin "git@gitlab.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git fetch
    - semver bump --git --apply
    - git push origin master --verbose --tags
  after_script:
    - rm -rf ~/.ssh/*



compress:
  stage: package
  only: ["tags"]
  # allow failure because it's not necessary to always compress
  # even though that would be nice
  allow_failure: true
  dependencies: ["build"]
  artifacts:
    expire_in: 1 day
    paths: ["./bin/*"]
  before_script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y make g++ upx
  script:
    - GOOS=linux GOARCH=amd64 make compress_production
    - GOOS=darwin GOARCH=amd64 make compress_production
    - GOOS=windows GOARCH=386 BIN_EXT=.exe make compress_production

dockerize:
  stage: package
  only: ["tags"]
  services: ["docker:19.03.1-dind"]
  image: usvc/ci:docker-build
  dependencies: ["build"]
  artifacts:
    expire_in: 1 day
    paths: ["./build/*"]
  variables:
    IMAGE_URL: usvc/libeg-config:latest
    OUTPUT_PATH: ./build/config.tar.gz
  script:
    - mkdir -p ./build
    - entrypoint

dockerhub:
  stage: publish
  services:
    - docker:19.03.1-dind
  image: docker:19.03.1
  dependencies:
    - dockerize
  only:
    - tags
  before_script:
    - apk add git jq make
    - docker login ${DOCKER_REGISTRY_URL:-docker.io} -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
  script:
    - make load
    - make dockerhub
  after_script:
    - docker logout
    - rm -rf ~/.docker/config.json
