schemaVersion: "2.0.0"
fileExistenceTests:
  - name: "binary"
    path: "/"
    shouldExist: true
commandTests:
  - name: "binary is in path"
    command: "/semver"
    args: ["--version"]
    expectedOutput: ["semver version"]
